### ISSUE TITLE
Day 6 - EDA notebook link is not working

### ISSUE THREAD

**Issue by ry-v1** [dphi-official/five-week-data-science-bootcamp#1]
House Prices Notebook link https://www.kaggle.com/pavansanagapati/a-simple-tutorial-on-exploratory-data-analysis/notebook is redirecting to 404. I have tried checking in the user kaggle's "code".

**Comment by chanukyapatnaik** [comment]
@ry-v1 thank you for reporting. Fixed this issue and updated it with a new resource link.
